name: Deploy to GKE

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GCR
        uses: google-github-actions/auth@v0
        with:
          gcr: true
          service_account_key: ${{ secrets.GKE_SA_KEY }}

      - name: Build Docker Image
        run: |
          docker buildx build \
            --tag gcr.io/${{ secrets.GKE_PROJECT }}/your-app-name:${{ github.sha }} \
            --tag gcr.io/${{ secrets.GKE_PROJECT }}/your-app-name:latest \
            .

      - name: Push Docker Image to GCR
        run: |
          docker push gcr.io/${{ secrets.GKE_PROJECT }}/student-app:${{ github.sha }}
          docker push gcr.io/${{ secrets.GKE_PROJECT }}/student-app:latest

  deploy:
    name: Deploy to GKE
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up GCloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
          export_default_credentials: true

      - name: Configure Docker Authentication
        run: |
          gcloud auth configure-docker

      - name: Deploy to GKE
        run: |
          kubectl apply -f path/to/your/kubernetes/configs/
