name: Prod Build and Push Advertisers API
on:
  push:
    branches: [main]
    
env:
  IMAGE: students
  PROJECT_ID: speedy-district-413015
  GKE_CLUSTER: autopilot-cluster-1
  GKE_ZONE: asia-south1
  DEPLOYMENT_NAME: students-depl
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'Authorize GCloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
        gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Build Docker Image
      run: |-
        docker build \
          --tag "asia-south1-docker.pkg.dev/$PROJECT_ID/students/$IMAGE:$GITHUB_SHA" \
          --tag "asia-south1-docker.pkg.dev/$PROJECT_ID/students/$IMAGE:latest" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          -f Dockerfile .

    - name: Push Docker Image to Artifact Registry
      run: |-
        docker push asia-south1-docker.pkg.dev/$PROJECT_ID/students/$IMAGE --all-tags

    - name: Restart Deployment
      run: |-
        kubectl rollout restart deployment $DEPLOYMENT_NAME
